parameters:
- name: agentTag
  displayName: Agent Tag
  type: string

jobs:
- deployment: 'DeployEnvironment'
  displayName: 'Test Job'
  condition: succeeded()
  environment:
    name: ci2
    resourceType: virtualMachine
    # BUG: Though documented, multiple tags don't seem possible
    # https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#environment
    # tags: string | [ string ] # tag names to filter the resources in the environment
    # tags: $(agentTag) $(resourceSuffix)
    tags:  ${{ parameters.agentTag }}

  strategy:
    runOnce:
      deploy:
        steps:
        - pwsh: |
            Write-Host "Hello Task"
            Write-Host "Tags: ${{ parameters.agentTag }}"
          displayName: 'Test task'
