parameters:
- name: region
  displayName: Azure Region
  type: string
  default: westeurope
  values:
  - eastus
  - westeurope
- name: workspace
  displayName: Pipeline Environment / Terraform Workspace
  type: string
  default: rel
  values:
  - rel
  - rel1
  - rel2
  - rel3
- name: destroy
  displayName: Destroy infrastructure
  type: string
  default: Never
  values:
  - Never 
  - 'On failure'
  - 'On success'
- name: testMode
  displayName: Test Mode (disable most tasks)
  type: boolean
  default: false

trigger: none 

pr: none

resources:
  pipelines:
  - pipeline: 'ci'
    source: vdc-terraform-apply-ci
  # branch: master

variables:
- template: ./templates/vdc-terraform-apply.variables.yml
  # This pipeline assumes TF_VAR_* variables are defined in Variable Groups defined in Library
  # The Terraform VDC project requires quite a number of settings
- group: 'vdc-release'
- name: 'TF_VAR_build_id'
  value: '$(resources.pipeline.ci.runID)'
- name: 'TF_VAR_release_id'
  value: '$(Build.BuildId)'
- name: 'TF_VAR_release_user_email'
  value: '$(Build.RequestedForEmail)'
- name: 'TF_VAR_release_web_url'
  value: '$(System.TeamFoundationCollectionUri)/$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&view=results'
- name: 'TF_VAR_resource_suffix'
  value: 'r$(Build.BuildId)'
  
stages:
- template: ./templates/vdc-terraform-apply.yml
  parameters:
    name: 'Release'
    displayName: 'VDC Release'
    inherit: true
    provision: true
    reprovision: false
    deploy: true
    deploymentName: 'demo'
    destroy: ${{ parameters.destroy }}
    region: ${{ parameters.region }}
    testMode: ${{ parameters.testMode }}
    vdcArtifactPipeline: 'ci'
    workspace: ${{ parameters.workspace }}