# This pipeline performs a full CI test of the VDC:
#  - Provision infrastructure
#  - Deploy application
#  - Test application
#  - Destroy infrastructure

parameters:
- name: workspace
  displayName: Terraform Workspace
  type: string
  default: ci
  values:
  - ci
  - ci1
  - ci2
  - ci3
- name: testMode
  displayName: Test Mode (disable most tasks)
  type: boolean
  default: true

# trigger:
#   batch: true
#   branches:
#     include:
#     - master
#   paths:
#     include:
#     - 'scripts/*' 
#     - 'terraform/*' 
#     exclude:
#     - '*.md'
#     - '*.png'  
#     - '*.svg'  
#     - '*.vsdx'  
#     - 'apps/*'
#     - 'kusto/*'
#     - 'pipelines/*'

# pr:
#   branches:
#     include:
#     - '*'
#   paths:
#     exclude:
#     - '*.md'  
#     - '*.png'  
#     - '*.svg'  
#     - '*.vsdx'  

# schedules:
# - cron: '0 3 * * *'
#   displayName: 'Daily early morning build (UTC)'
#   # Run if there are no changes
#   always: 'true'
#   branches:
#     include:
#     - master

variables:
- template: ./templates/vdc-terraform-apply.variables.yml
  # This pipeline assumes TF_VAR_* variables are defined in Variable Groups defined in Library
  # The Terraform VDC project requires quite a number of settings
- group: 'vdc-ci'
- name: 'TF_VAR_resource_suffix'
  value: 'b$(Build.BuildId)'

stages:
- template: ./templates/vdc-terraform-apply.yml
  parameters:
    name: 'CI'
    displayName: 'VDC CI'
    inherit: false
    provision: true
    reprovision: true
    deploy: true
    destroy: true
    testMode: ${{ parameters.testMode }}
    workspace: ${{ parameters.workspace }}