parameters:
- name: workspace
  displayName: Pipeline Environment / Terraform Workspace
  type: string
  default: cd1
  values:
  - cd1
  - cd2
  - cd3
- name: destroy
  displayName: Destroy resources
  type: boolean
  default: false
- name: testMode
  displayName: Test Mode (disable most tasks)
  type: boolean
  default: true
trigger: none 

pr: none

variables:
- template: ./templates/vdc-terraform-apply.variables.yml
  # This pipeline assumes TF_VAR_* variables are defined in Variable Groups defined in Library
  # The Terraform VDC project requires quite a number of settings
- group: 'vdc-release'
- name: 'ciPipelineAlias'
  value: 'ci'
- name: 'TF_VAR_resource_suffix'
  value: 'r$(Build.BuildId)'

resources:
  pipelines:
  - pipeline: '$(ciPipelineAlias)'
    source: vdc-terraform-apply-ci
  # branch: master
  
stages:
- template: ./templates/vdc-terraform-apply.yml
  parameters:
    name: 'Release'
    displayName: 'VDC Release'
    inherit: true
    provision: true
    reprovision: false
    deploy: true
    destroy: ${{ parameters.destroy }}
    testMode: ${{ parameters.testMode }}
    vdcArtifactPipeline: '$(ciPipelineAlias)'
    workspace: ${{ parameters.workspace }}