# This pipeline performs a limited CI test of the VDC:
#  - Plan infrastructure i.e. check for Terraform validation errors

trigger:
  branches:
    include:
    # Trigger on every branch, as this pipeline executes around 1 minute
    - '*'
  paths:
    include:
    - 'Terraform/*' 
    exclude:
    - 'Apps/*'
    - 'Kusto/*'
    - 'Pipelines/*'

pr:
  branches:
    exclude:
    # Already triggering on every commit on any branch
    - '*'

# Global variables shared by all jobs
variables:
  # Variable Groups are referenced, but defined elsewhere (Library)

  # This pipeline assumes TF_VAR_* variables are defined in Variable Groups defined in Library
  # The Terraform VDC project requires quite a number of settings, see:
  # https://github.com/geekzter/azure-vdc/blob/master/Terraform/variables.tf
  # https://github.com/geekzter/azure-vdc/blob/master/Terraform/config.auto.tfvars.sample
  # https://github.com/geekzter/azure-vdc/blob/master/Terraform/ci.tfvars
  # i.e. settings in these files should be captured in (a) variable group(s)
  # These can be provided as TF_VAR_<input-variable> environment variables:
  # https://www.terraform.io/docs/configuration/variables.html#environment-variables
  # 'vdc' contains global settings common to all VDC pipelines
- group: 'vdc'
  # 'vdc-ci' contains build (non-release) settings
- group: 'vdc-ci'
  # 'vdc-vanity-domain' contains certificate, domain information
- group: 'vdc-vanity-domain'


# Inline variables shared across jobs
- name: 'scriptDirectory'
  value: '$(Build.SourcesDirectory)/Scripts'
- name: 'TF_IN_AUTOMATION'
  value: 'true'
- name: 'TF_INPUT'
  value: 0
- name: 'TF_WORKSPACE'
  value: 'cip'

jobs:
- job: 'Plan'
  displayName: 'Plan Infrastructure with Terraform'
  timeoutInMinutes: $[ variables['jobTimeOutMinutes'] ]

  pool:
    vmImage: 'ubuntu-latest'

  workspace:
    clean: all

  steps:
    - task: DownloadSecureFile@1
      displayName: 'Download SSL certificate'
      inputs:
        secureFile: '$(TF_VAR_vanity_certificate_path)'

    - task: DownloadSecureFile@1
      displayName: 'Download VPN root certificate'
      inputs:
        secureFile: '$(TF_VAR_vpn_root_cert_file)'

    - task: AzureCLI@2
      displayName: 'Gather Terraform settings'
      name: terraformConfig
      inputs:
        azureSubscription: '$(subscriptionConnection)'
        scriptType: pscore
        scriptLocation: inlineScript
        # ARM_* environment variables are required by Terraform azurerm provider and backend
        # https://www.terraform.io/docs/providers/azurerm/index.html
        # https://www.terraform.io/docs/backends/types/azurerm.html
        # Use Pipeline Service Principal and Service Connection to set up these variables
        inlineScript: |
          $env:ARM_CLIENT_ID=$env:servicePrincipalId
          $env:ARM_CLIENT_SECRET=$env:servicePrincipalKey
          $env:ARM_SUBSCRIPTION_ID=$(az account show --query id | tr -d '\"')
          $env:ARM_TENANT_ID=$env:tenantId
          # List environment variables (debug)
          if ((${env:system.debug} -eq "true") -or ($env:system_debug -eq "true") -or ($env:SYSTEM_DEBUG -eq "true")) {
            Get-ChildItem -Path Env:ARM_* | Sort-Object -Property Name
          }
          Write-Host "##vso[task.setvariable variable=clientId;isOutput=true]$env:ARM_CLIENT_ID"
          Write-Host "##vso[task.setvariable variable=clientSecret;isOutput=true]$env:ARM_CLIENT_SECRET"
          Write-Host "##vso[task.setvariable variable=subscriptionId;isOutput=true]$env:ARM_SUBSCRIPTION_ID"
          Write-Host "##vso[task.setvariable variable=tenantId;isOutput=true]$env:ARM_TENANT_ID"

          # This will write version info as output variable
          $(scriptDirectory)/get_tf_version.ps1 -version preferred
        addSpnToEnvironment: true
        useGlobalConfig: true
        failOnStandardError: true

    # We could do this with tfenv, however there is no task for that
    - task: TerraformInstaller@0
      displayName: 'Use preferred Terraform version'
      inputs:
        terraformVersion: '$(terraformConfig.version)'

    - task: AzurePowerShell@4
      # Name is required so Terraform output exported by tf_deploy.ps1 can be referenced by subsequent Pipeline steps
      name: terraform 
      displayName: 'Terraform init & plan'
      inputs:
        azureSubscription: '$(subscriptionConnection)'
        ScriptType: 'FilePath'
        # tf_deploy.ps1 is a wrapper around, and invokes, Terraform
        ScriptPath: '$(scriptDirectory)/tf_deploy.ps1'
        # To start from scratch, use these arguments:
        ScriptArguments: '-init -plan -trace $(trace) -parallelism $(parallelism)'
        FailOnStandardError: true
        azurePowerShellVersion: 'LatestVersion'
        pwsh: true
      env:
        # Use prepared Terraform environment variables
        ARM_CLIENT_ID: '$(terraformConfig.clientId)'
        ARM_CLIENT_SECRET: '$(terraformConfig.clientSecret)'
        ARM_SUBSCRIPTION_ID: '$(terraformConfig.subscriptionId)'
        ARM_TENANT_ID: '$(terraformConfig.tenantId)'
